import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import type { TransactionWithBalance } from "@/lib/types";
import { categoryLabel } from "@/lib/domain/categories";
import { formatCents } from "@/lib/domain/money";
import { totalsCents } from "@/lib/domain/ledger";

/** QuickEntry / Interlock UI palette (RGB for jsPDF) */
const BRAND: [number, number, number] = [232, 55, 27];
const TEXT: [number, number, number] = [15, 23, 42];
const MUTED: [number, number, number] = [100, 116, 139];
const SUCCESS: [number, number, number] = [4, 120, 87];
const DANGER: [number, number, number] = [185, 28, 28];
const HEADER_BG: [number, number, number] = [241, 245, 249];
const BORDER: [number, number, number] = [226, 232, 240];
const STRIPE: [number, number, number] = [248, 250, 252];

function parseTxnDate(iso: string): Date {
  const [y, m, d] = iso.split("-").map(Number);
  return new Date(y!, m! - 1, d!);
}

function formatTxnDateShort(iso: string): string {
  return parseTxnDate(iso).toLocaleDateString("en-GB", {
    day: "2-digit",
    month: "short",
    year: "2-digit",
  });
}

function formatDateLong(d: Date): string {
  return d.toLocaleDateString("en-GB", {
    day: "2-digit",
    month: "short",
    year: "numeric",
  });
}

function formatDurationRange(rows: TransactionWithBalance[]): string {
  if (rows.length === 0) return "—";
  const ts = rows.map((r) => parseTxnDate(r.txn_date).getTime());
  const min = new Date(Math.min(...ts));
  const max = new Date(Math.max(...ts));
  return `${formatDateLong(min)} - ${formatDateLong(max)}`;
}

function formatGeneratedOn(d: Date): string {
  return d.toLocaleString("en-GB", {
    day: "2-digit",
    month: "short",
    year: "numeric",
    hour: "numeric",
    minute: "2-digit",
    hour12: true,
  });
}

function moneyPdf(cents: number): string {
  return formatCents(cents);
}

export type CashbookPdfOptions = {
  rows: TransactionWithBalance[];
  generatedByEmail: string | null;
  /** Printed under main title — e.g. business name */
  organizationLine?: string;
};

/**
 * Builds a CashBook-style multi-page PDF: summary block + ledger table +
 * repeating header row, branded for QuickEntry.
 */
export function buildCashbookPdf(options: CashbookPdfOptions): jsPDF {
  const { rows, generatedByEmail, organizationLine } = options;
  const now = new Date();
  const { receipts, payments } = totalsCents(rows);
  const finalBalance =
    rows.length > 0 ? rows[rows.length - 1].running_balance_cents : 0;

  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
  });

  const pageW = doc.internal.pageSize.getWidth();
  const margin = 14;
  let y = 16;

  doc.setFillColor(...BRAND);
  doc.rect(0, 0, pageW, 6, "F");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.setTextColor(...BRAND);
  doc.text("QUICKENTRY", margin, y);
  doc.setFontSize(11);
  doc.setTextColor(...MUTED);
  doc.text("Cash ledger report", margin + 52, y);

  y += 8;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(...TEXT);
  if (organizationLine?.trim()) {
    doc.text(organizationLine.trim(), margin, y);
    y += 5;
  }

  doc.setTextColor(...MUTED);
  const by =
    generatedByEmail?.trim() ||
    "(signed-in user)";
  doc.text(
    `Generated on — ${formatGeneratedOn(now)} · Generated by — ${by}`,
    margin,
    y,
  );
  y += 9;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.setTextColor(...TEXT);
  doc.text("Cash ledger", margin, y);
  y += 6;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(...MUTED);
  doc.text(`Duration: ${formatDurationRange(rows)}`, margin, y);
  y += 5;

  doc.setTextColor(...TEXT);
  doc.text(`Total cash in   ${moneyPdf(receipts)}`, margin, y);
  y += 5;
  doc.text(`Total cash out  ${moneyPdf(payments)}`, margin, y);
  y += 5;
  doc.setTextColor(...SUCCESS);
  doc.text(`Final balance   ${moneyPdf(finalBalance)}`, margin, y);
  doc.setTextColor(...TEXT);
  y += 5;
  doc.text(`Total no. of entries: ${rows.length}`, margin, y);
  y += 6;

  const body: string[][] = rows.map((row) => [
    formatTxnDateShort(row.txn_date),
    row.description?.trim() || "—",
    categoryLabel(row.category),
    row.type === "in" ? "Receipt" : "Payment",
    row.type === "in" ? moneyPdf(row.amount_cents) : "",
    row.type === "out" ? moneyPdf(row.amount_cents) : "",
    moneyPdf(row.running_balance_cents),
  ]);

  if (rows.length > 0) {
    body.push([
      formatTxnDateShort(rows[rows.length - 1].txn_date),
      "Final balance",
      "",
      "",
      "",
      "",
      moneyPdf(finalBalance),
    ]);
  }

  autoTable(doc, {
    startY: y,
    head: [
      [
        "Date",
        "Remark",
        "Category",
        "Type",
        "Cash in",
        "Cash out",
        "Balance",
      ],
    ],
    body,
    showHead: "everyPage",
    styles: {
      font: "helvetica",
      fontSize: 8,
      cellPadding: 2,
      textColor: TEXT,
      lineColor: BORDER,
      lineWidth: 0.1,
    },
    headStyles: {
      fillColor: HEADER_BG,
      textColor: TEXT,
      fontStyle: "bold",
      halign: "left",
    },
    columnStyles: {
      0: { cellWidth: 22 },
      1: { cellWidth: 46 },
      2: { cellWidth: 22 },
      3: { cellWidth: 18 },
      4: { halign: "right", cellWidth: 22, textColor: SUCCESS },
      5: { halign: "right", cellWidth: 22, textColor: DANGER },
      6: { halign: "right", cellWidth: 24, fontStyle: "bold" },
    },
    alternateRowStyles: { fillColor: STRIPE },
    margin: { left: margin, right: margin, bottom: 18 },
    tableWidth: pageW - 2 * margin,
  });

  const totalPages = doc.getNumberOfPages();
  const footY = doc.internal.pageSize.getHeight() - 10;

  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(...MUTED);
    doc.text("Generated by QuickEntry", margin, footY);
    doc.text(`— ${i} of ${totalPages} —`, pageW / 2, footY, {
      align: "center",
    });
  }

  return doc;
}

/** Save with a filename similar to CashBook exports */
export function downloadCashbookPdf(options: CashbookPdfOptions): void {
  const stamp = new Date()
    .toISOString()
    .slice(0, 19)
    .replace(/[T]/g, "_")
    .replace(/:/g, "-");
  const doc = buildCashbookPdf(options);
  doc.save(`Ledger_${stamp}@CashBook.pdf`);
}
